
export const AJOUTER_FORM_PAGE = 'AJOUTER_FORM_PAGE'
export const INGREDIENT_LIST = 'INGREDIENT_LIST'
export const UPDATE_STEP_LIST = 'UPDATE_STEP_LIST'
export const AJOUTER_FORM_DESCRIPTION = 'AJOUTER_FORM_DESCRIPTION'
